<?php
$infoArray = $this->getOrder()->getPayment()->getAdditionalInformation();
$ssku = '';

if (array_key_exists('service_sku', $infoArray)) {
    $ssku = $infoArray['service_sku'];
    echo "The order was imported from " . $this->channelSkuToName($ssku) . ".<br/>";
}
if (array_key_exists('order_flags', $infoArray)) {
    $orderFlags = $infoArray['order_flags'];
    // Spit out known information
    if (strpos($orderFlags, "AMAZON_FBA") !== false) {
        echo "Order was fulfilled by Amazon.<br/>";
    }
    if (strpos($orderFlags, "AMAZON_PRIME") !== false) {
        echo "<strong>Seller Fulfilled Prime</strong><br/>";
    }
    
    $parsedOrderFlags = json_decode($orderFlags, true);
    if (is_array($parsedOrderFlags) && array_key_exists('customer_number', $parsedOrderFlags)) {
        $customerNumber = $parsedOrderFlags['customer_number'];
        if ($ssku == 'CU_ZALANDO_COM') {
            echo "<strong>Zalando Customer Number: $customerNumber</strong><br/>";
        }
    }
    
}
?>
